### PR TITLE
Fix #1364 Error while parsing SVG with path tag

### LINKED ISSUE #1364: Error while parsing SVG with path tag
Hi!
I have an SVG:
`<svg width="600" height="600"><path d="M 330,0 L 330, 600" style="stroke:red;"></path></svg>`

When I've tried to parse it with canvg I've got an error:
Uncaught SyntaxError: Invalid number ending at 14
image

image

I guess the problem is here:
https://github.com/canvg/canvg/blob/0af507c6419e56dbd2b6d10c1855faab4220ce81/src/PathParser.ts#L47

there we have a regExp like:
`[+-.]\s+`
which means: a single character in the range between + (index 43) and . (index 46) (case sensitive) and one or more of any whitespace characters.

**I guess author wanted to implement a bit another idea like:**
`[+\-.]\s+`

What do you think?

image

### PR DESCRIPTION
**Pull request by zarikadzer**
RegExp updated

### CODE REVIEW

**Comment by gabelerner** [comment]
definitely looks like a bug! i have a new child at home, @dangreen can you review/approve/merge please?

**Comment by dangreen** [comment]
@zarikadzer  You should update snapshots.

1) make commit with `[ci update snapshots]` in message
2) wait when new snapshots will generated
3) download new snapshots from artifacts https://github.com/canvg/canvg/actions/runs/618394658
4) make commit with new snapshots

**Comment by zarikadzer** [comment]
> @zarikadzer Small update: new screenshots will generated in your fork
> 
> > wait when new snapshots will generated
> > download new snapshots from artifacts
> 
> https://github.com/zarikadzer/canvg/actions/runs/638637371

**done!**

note: I've not updated snapshots of issue869 because it definitely contains errors.
image

**Comment by zarikadzer** [comment]
@gabelerner @dangreen Any other comments?

**Comment by dangreen** [comment]
@zarikadzer Please update snapshots of issue869 too.

**Comment by zarikadzer** [comment]
@dangreen done

File: src/PathParser.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export default class PathParser extends SVGPathData {
 		super(
 			path
 				// Fix spaces after signs.
-				.replace(/[+-.]\s+/g, '-')
+				.replace(/[+\-.]\s+/g, '-')
```
Comment (dangreen) [inline src/PathParser.ts:47]:
```suggestion
				.replace(/([+\-.])\s+/g, '$1')
```

?

**Review by dangreen — APPROVED** [review]

File: src/PathParser.ts (hunk 1 above)
Comment (zarikadzer) [reply src/PathParser.ts:47]:
```suggestion
				.replace(/([+-.])\s+/gm, '$1')
```
In case of trimming white spaces I guess such expression could be better. What do you think?

Comment (dangreen) [reply src/PathParser.ts:47]: yep

**Comment by zarikadzer** [comment]
@dangreen done

**Comment by zarikadzer** [comment]
@dangreen any suggestions?

**Comment by dangreen** [comment]
@zarikadzer sorry, I'll see tomorrow

File: src/PathParser.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ export default class PathParser extends SVGPathData {
 		super(
 			path
 				// Fix spaces after signs.
-				.replace(/[+-.]\s+/g, '-')
+				.replace(/([+-.])\s+/gm, '$1')
```
Comment (dangreen) [inline src/PathParser.ts:47]:
```suggestion
				.replace(/([+\-.])\s+/gm, '$1')
```

?

Comment (zarikadzer) [reply src/PathParser.ts:47]: I suppose that symbols **+-.** and **,** can be surrounded by lot of whitespaces so ([+-.])\s+ will trim spaces after all of 4 symbols.

Comment (dangreen) [reply src/PathParser.ts:47]: there no need to trim spaces around commas

Comment (zarikadzer) [reply src/PathParser.ts]: Ok I've committed your suggestion.

**Review by dangreen — APPROVED** [review]
